### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create an `index.html` file and add a HTML skeleton
- [x] Create a `styles.css` file and link it to `index.html`
- [x] Add the image of the car to the HTML
- [x] Add CSS styling to set the background color of the screen to the specified shade of green
- [x] Make sure that the car is sized and positioned the same as in the provided example
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Fix all errors
