### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a `main.js` file and link it to `index.html`
- [x] Listen for `keydown` events on the `document` for the right and left arrow keys
- [x] Use the CSS `transform` property to have the image of the car rotate with the `keydown` event
- [x] Store the value of the direction the car is facing (North, South, East, or West)
- [x] Use the CSS `transition` property to make the car rotate smoothly
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Fix all errors
