### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add a condition to the event listener function to listen for the spacebar key
- [x] Set the `display` property of the car image to `absolute`
- [x] Store the car's location using its x and y coordinates on the page
- [x] Use the `style` property of element objects to change the car's `top` and `left` box offset styles
- [x] Set the car to move every `16` milliseconds
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Fix all errors
