### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to the data model to indicate whether or not the car is started
- [x] Adjust the `startCar` function so that if the car is started, pressing the space bar will stop the car
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary
- [x] Fix all errors
