### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Adjust the `startCar()` function to update the car's `top` and `left` properties according to the direction the car is facing
- [x] Ensure that the car is able to start again after it has been stopped
- [x] Check that the car is able to rotate smoothly in any direction
- [x] Remove all CSS styling that has no effect or was otherwise unnecessary
- [x] Fix all errors
